
update site set occupational_category='35-2011 Cooks, Fast Food' ;


Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew                                                                                                  ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Maintenance Person';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Person ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager ';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'General Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Department Manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Maintenance ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Guest Experience Lead GEL ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Manager Trainee ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Starting Pay Up To $13.50 hr ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Members';
Update site set occupational_category = '35-9099 Food Preparation and Serving Related Workers, All Other' where job_title = 'Part Time crew';
Update site set occupational_category = '35-2011 Cooks, Fast Food' where job_title = 'Part Time and Full Time Crew';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Fast Food ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Cashier ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Hiring Now';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Full Time Crew';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Cook';
Update site set occupational_category = '37-1010 First-Line Supervisors of Building and Grounds Cleaning and Maintenance Workers' where job_title = 'Food and Restaurant ';
Update site set occupational_category = '' where job_title = '$15.50 Starting Wage Maintenance Person';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew $14.00 Starting Wage';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 13838 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  13838 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 4061';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  4061';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 31049 ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = '$13 Hour and Up to Start';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'CREW MEMBER ';
Update site set occupational_category = '35-9099 Food Preparation and Serving Related Workers, All Other' where job_title = 'Crew  Free money for college? Ask us how!';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Maintenance Lobby ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Kitchen ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Overnight Cashier Kitchen ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Assistant Manager ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Crew Starting Pay Up To $12.50 hr ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew $13.00 Starting Wage';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew $12.00 Starting Wage';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Maintenance  countryside';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'countryside Guest Experience Lead GEL ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'countryside crew team member';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 5813';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  5813';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  24955 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 24955 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 4811';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  4811';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  6350';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 6350';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  10016 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 10016 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  961 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 961 ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Copy  Shift Manager';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Copy  Guest Experience Lead GEL';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Copy  Maintenance';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'PartTime Overnight Crew Person ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Guest Experience Leader ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew 1';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restaurant Crew up to $12.50 an hourCollege Benefits ';
Update site set occupational_category = '49-0000 Installation, Maintenance, and Repair Occupations' where job_title = 'FullTime Maintenance $13.00 hr ';
Update site set occupational_category = '49-9090 Miscellaneous Installation, Maintenance, and Repair Workers' where job_title = 'Maintenance Person $12.00 hr College Benefits!! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Starting $11 hr. overnight up to $12.00 hr*';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Up to $12.00 hr Overnight Crew Team Member up to $12.00 hr. College Benefits!!! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Grill Team Member ';
Update site set occupational_category = '37-1011 First-Line Supervisors of Housekeeping and Janitorial Workers' where job_title = 'Janitorial Position $14.00 Full Time Mornings ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager $14.00$17.00 per hr. ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Full Time $13.50 hr. Team Member 40 Hrs. Position ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Part Time Team Member 11a.m.  6p.m. $13.50 hr. Position';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Part Time Team Member 5a.m.  10a.m. $13.50 hr. Position';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = '$13.50 hr. Full Time 40hr Crew Member Position';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew $11.00 Starting Wage';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Hourly Team member';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Crew Starting Pay Up To $12 hr';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Afternoon Crew Team Member';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Morning Crew Team Member';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'CREWNOW HIRING AT UP TO $12.00 DOLLARS PER HOUR';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Shift ManagerNOW HIRING AT UP TO $14.00 DOLLARS PER HOUR ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew 2';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'CREWNOW HIRING AT UP TO $11.00 DOLLARS PER HOUR';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'supervisor';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'McDonald''s Crew ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'V3 Crew Team Member ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew $10.00 Starting Wage';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = '2Day Maintenance ';
Update site set occupational_category = '49-9040 Industrial Machinery Installation, Repair, and Maintenance Workers' where job_title = 'Equipment and Facilities Technician ';
Update site set occupational_category = '49-1000 Supervisors of Installation, Maintenance, and Repair Workers' where job_title = 'Maintenance Technician';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restaurant Manager';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Concierge ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Housekeeper ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restaurant Team Member';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Copy  Crew Team Member ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Area Supervisor ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Overnight Shift  Crew';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Morning Shift  Crew';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Night Shift  Crew';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Table Service ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Positions! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Copy  Department Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Closers ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Hourly Manager Postiions Available! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Career Manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Salary Manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Custodian ';
Update site set occupational_category = '49-0000 Installation, Maintenance, and Repair Occupations' where job_title = 'Maintenance Position';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Member McDonald''s';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Closer: Up to $9.00 per hour 3pm to Close';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew Positon  3pm start time ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Maintenance Position Weekends Saturday & Sunday';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Guest Experience Lead Salary: $10 hour 7am to 3pm ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'FIRST ASSISTANT  up to $45000 with experience ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Operner: 4am to Noon';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'Shift Manager  up to $15 hr opening closing shifts & availability';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Closer: up to $10 per hour  See store GM for details ';
Update site set occupational_category = ' Hlth Insurance' where job_title = '1st Assistant Mgr. up to $45000 salary';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Dayside crew positions 6am2pm and 11am7pm';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'Shift Manager up to $14 hour for premium shifts & availability & mgmt experience required';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'Copy  Crew Team Member  up to $10 hr with dependable availability ';
Update site set occupational_category = '49-9099 Installation, Maintenance, and Repair Workers, All Other' where job_title = 'Maintenance Full Time  up to $15 hr with experience';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Position: Up to $10';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew  3pm to Midnight';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Closer: up to $9 per hour  See store GM for details';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew positon 11am  7pm';
Update site set occupational_category = '11-3012 Administrative Services Managers' where job_title = '1st Assistant Manager Up to $45000 salary  McDONALD MANAGEMENT EXPERIENCE REQUIRED ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Opener: Up to $9.00 per hour 4am to Noon ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Closer';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = '2nd Assistant Manager $36000 to $42000 with McDonald''s Mgmt Experience';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Opener: $10 hr with McDonald''s Experience ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'SECOND ASSISTANT  up to $38000 with experience';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Shift Manager Opener Closer';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Closer: Up to $9.25 hr  Hours: 3pm  Close ';
Update site set occupational_category = ' with benefits ' where job_title = 'Maintenance Position: MF & or Sat. & Sun up to $13 hr';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew Overnight Position up to $10 hr';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Maintenance Position Weekends Saturday & Sunday 5am2pm';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Nightside Positions Available: 4pm  10pm ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Opener: Up to $9.25 hr. Hours: 4am  Noon.';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Afternoon Crew starting at 11am ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Overnight Crew starting at 10pm ';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'Management Opportunities Available';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Morning Crew starting at 6am';
Update site set occupational_category = '49-9099 Installation, Maintenance, and Repair Workers, All Other' where job_title = 'Facilities Maintenance starting $10 Multiple Locations Available Must be 18+ ';
Update site set occupational_category = '11-9033 Education Administrators, Postsecondary' where job_title = 'College University Students Wanted Scholarships Available ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Certified McDonald''s Manager';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Crew Person  Overnights';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Store Openers starting at 5am ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Customer Experience Lead up to $10 per Hour ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Overnight Crew Fri & Sat starting at 10pm ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew  2pm to 11pm up to $10 hr at our St. John location ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Opener: $10 hr';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew 3:45pm  10pm up to $10 hr at our St. John location';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew for overnights 9pm to 6am up to $10 hr at our St. John location';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Dayside crew position: Monday  Friday 6a  4p parttime or fulltime ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Overnight Position ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Closer: 3pm to close';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew 5am3pm up to $10 hr at our St. John location';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Store Closers starting at 4pm ';
Update site set occupational_category = '49-9090 Miscellaneous Installation, Maintenance, and Repair Workers' where job_title = 'Maintenance MF up to $12 hr';
Update site set occupational_category = '49-9090 Miscellaneous Installation, Maintenance, and Repair Workers' where job_title = 'Maintenance Weekends up to $12 hr ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Team Member ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member Overnight ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Hospitality Ambassador   Host  Hostess';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Team Lead  Shift Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Team Member  Crew';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Team Member Hiring Day';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'NOW HIRING';
Update site set occupational_category = '35-2011 Cooks, Fast Food' where job_title = 'Part Time and Full Time Fast Food ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restuarant Manager';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Guest Experience  Host or Hostess ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Day side Service Position ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'overnight crew manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 4111 ';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'TRACY  Crew Team Member';
Update site set occupational_category = '49-1000 Supervisors of Installation, Maintenance, and Repair Workers' where job_title = 'TRACY  Maintenance Technician';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'TRACY  Restaurant Manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'TRACY  Maintenance Person';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'TRACY  Shift Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'TRACY  Housekeeper ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'TRACY  Conceirge ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew Team Member Closing Shift';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew Team Member Opening Shift';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Certified Swing Manager ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Crew $14 Hour and Up to Start ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Overnight Crew Position ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Manager  6783';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Team Member 6783';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew Trainer';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Floor Supervisor';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'General Manager H ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Department Manager I';
Update site set occupational_category = '37-1000 Supervisors of Building and Grounds Cleaning and Maintenance Workers' where job_title = 'Custodian Maintenance  beginning ';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'Shift Support Manager Certified Swing Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Overnight Crew';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = '14 15 yr Old Guest Experience Lead GEL';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Copy  14 15 yr Old Guest Experience Lead GEL ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'McDonald''s Crew Person';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'McDonald''s  Overnight  Crew ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Grill Team  Day Shift';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'General Manager RLMK';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'Assistant General Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew  Closing';
Update site set occupational_category = '35-9010 Dining Room and Cafeteria Attendants and Bartender Helpers' where job_title = 'Crew Positions  make up to $14 an hour within 90 days';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Shift Manager Positions starting at $15.50 per hour ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Crew  Opening';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Cooks ';
Update site set occupational_category = '41-2010 Cashiers' where job_title = 'Cashiers';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Morning Crew Position ';
Update site set occupational_category = '49-9098 Helpers--Installation, Maintenance, and Repair Workers' where job_title = 'MAINTENANCE PERSONELL ';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'HOURLY MANAGERS ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'RESTAURANT DEPARTMENT MANAGERS';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Prep Person ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Customer Focused Employee ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Customer Focused Help ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Hostess & Guest Experience Leader ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'RestaurantShift Leader Up to $15 an hour!';
Update site set occupational_category = '11-1020 General and Operations Managers' where job_title = 'General Manager Starting at $45000 a year! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restaurant Food Service Worker up to $10 an hour! ';
Update site set occupational_category = '49-9070 Maintenance and Repair Workers, General' where job_title = 'Maintenance Person Up to $18 an hour! ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Restaurant Manager Up to $45000 a year!';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Store Manager ';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'OTP ';
Update site set occupational_category = '35-9030 Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop' where job_title = 'Guest Experience Lead ';
Update site set occupational_category = '51-3092 Food Batchmakers' where job_title = 'Food Preparation';
Update site set occupational_category = '11-9050 Food Service Managers' where job_title = 'Service Specialist';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Hourly Manager';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'Shift Leader';
Update site set occupational_category = '37-1000 Supervisors of Building and Grounds Cleaning and Maintenance Workers' where job_title = 'Custodian Maintenance Team Member ';
Update site set occupational_category = '11-9032 Education Administrators, Kindergarten through Secondary' where job_title = 'After Class for High School Students';
Update site set occupational_category = '35-2014 Cooks, Restaurant' where job_title = 'People Manager';
